Feature/ignore uncommitted changes
codacy/codacy-analysis-cli pull request #432
Opened 2021-12-05 17:53 UTC by dan-codacy

Adding this flag for a prospect. This is blocking their POC. The intent is to allow a client to ignore the uncommitted changes error that occurs when files are added to the repo directory during a build. 

The flag is false by default so the client will need to make the conscious choice to ignore this safety check.

2021-12-05 17:54 UTC, dan-codacy commented
I'm unsure as to why the tests are failing. I pulled down clean from master and they were failing even then. Any ideas?

2021-12-06 16:54 UTC, lolgab requested changes
A little nitpick, otherwise Good job! 💪

2021-12-06 16:54 UTC, lolgab commented on cli/src/main/scala/com/codacy/analysis/cli/command/CLIApp.scala
> +  @ExtraName("g") @ValueDescription("[default: false] - Skip the check for uncommitted files in the analysis directory")
Why `-g`?
I think you can avoid defining an `ExtraName` altogether and just allow the long option.
`skip-uncommitted-files-check` has not `g`ees :-D
```suggestion
  @ValueDescription("[default: false] - Skip the check for uncommitted files in the analysis directory")
```

2021-12-06 16:54 UTC, machadoit commented
> I'm unsure as to why the tests are failing. I pulled down clean from master and they were failing even then. Any ideas?

Not sure, seemed some timeout on something flaky, they are passing now. Other than the suggestion from @lolgab seems good to me! :D

2021-12-06 16:55 UTC, machadoit approved these changes

2021-12-06 16:58 UTC, dan-codacy commented
Thanks guys! Happy to remove the ExtraName def. I only chose -g because I
though it was required based on the previously added flags 😄

Just to confirm, we typically do a squash and merge, correct?



On Mon, Dec 6, 2021, 11:55 AM Joao Machado ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codacy/codacy-analysis-cli/pull/432#pullrequestreview-824210467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZXREQTE65SMEBZY42KB3TUPTTHZANCNFSM5JNAXTVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-06 17:15 UTC, lolgab approved these changes

2021-12-06 17:17 UTC, lolgab commented
Actually we use Merge commits usually. But we are not strict about it :)

2021-12-06 17:17 UTC, merged